<?php

declare(strict_types=1);

namespace Database\Factories;

use App\Models\Flight;
use App\Models\FlightLeg;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * Factory for Flight (the aggregate root).
 *
 * The `uuid` column is auto-generated by the HasUuids trait, so the factory's
 * base definition is intentionally empty. Helpers build out the nested tree.
 *
 * @extends Factory<Flight>
 */
final class FlightFactory extends Factory
{
    protected $model = Flight::class;

    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        // uuid is populated by HasUuids on insert; nothing else is required.
        return [];
    }

    /**
     * Build a complete flight: $legs legs, each with $segmentsPerLeg segments,
     * all correctly ordered. Mirrors the shape the create endpoint produces, so
     * tests can arrange a realistic flight in one call.
     */
    public function withTree(int $legs = 2, int $segmentsPerLeg = 2): self
    {
        return $this->afterCreating(function (Flight $flight) use ($legs, $segmentsPerLeg): void {
            for ($i = 1; $i <= $legs; $i++) {
                FlightLeg::factory()
                    ->for($flight)
                    ->order($i)
                    ->withSegments($segmentsPerLeg)
                    ->create();
            }
        });
    }
}
