<?php

declare(strict_types=1);

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Concerns\HasUuids;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;

/**
 * Flight aggregate root.
 *
 * A Flight is the top of our domain tree:
 *   Flight (1) ── (many) FlightLeg (1) ── (many) FlightSegment
 *
 * Publicly we identify a flight by its `uuid` (never the auto-increment `id`).
 *
 * @property int                                                              $id
 * @property string                                                           $uuid
 * @property \Illuminate\Support\Carbon                                       $created_at
 * @property \Illuminate\Support\Carbon                                       $updated_at
 * @property-read \Illuminate\Database\Eloquent\Collection<int, FlightLeg>    $legs
 */
final class Flight extends Model
{
    // HasFactory: enables Flight::factory() for tests/seeders.
    use HasFactory;

    // HasUuids: Laravel's trait that auto-generates a UUID on create. By default
    // it fills the model's primary key, but we override uniqueIds() below so it
    // populates our dedicated `uuid` column instead, leaving `id` as the
    // auto-incrementing internal key.
    use HasUuids;

    /**
     * The attributes that are mass assignable.
     *
     * We intentionally do NOT include `uuid` here because it is generated by the
     * framework (via HasUuids), not supplied by callers. Keeping the fillable
     * list tight prevents mass-assignment surprises.
     *
     * @var list<string>
     */
    protected $fillable = [];

    /**
     * Columns that should receive an auto-generated UUID.
     *
     * Overriding this from HasUuids tells Laravel: "generate a UUID for `uuid`,
     * not for the primary key." This is the idiomatic way to keep a numeric PK
     * while still auto-filling a separate UUID column on insert.
     *
     * @return list<string>
     */
    public function uniqueIds(): array
    {
        return ['uuid'];
    }

    /**
     * The column used for implicit route-model binding.
     *
     * With this, a route like `/api/flights/{flight}` resolves the {flight}
     * wildcard against the `uuid` column instead of the default `id`, so the
     * public UUID in the URL maps straight to a Flight model.
     */
    public function getRouteKeyName(): string
    {
        return 'uuid';
    }

    /**
     * A flight has many legs.
     *
     * Ordered by `leg_order` so the relationship always returns legs in their
     * submitted sequence — essential for the positional update-matching strategy
     * and for producing a stable GET response.
     */
    public function legs(): HasMany
    {
        return $this->hasMany(FlightLeg::class)->orderBy('leg_order');
    }

    /**
     * Scope: eager-load the full nested tree (legs + their segments) in the
     * correct order.
     *
     * Centralizing this here avoids repeating the same `with([...])` graph in
     * every controller/service and guarantees consistent ordering everywhere.
     *
     * Usage: Flight::withFullTree()->where('uuid', $uuid)->first();
     */
    public function scopeWithFullTree(Builder $query): Builder
    {
        return $query->with([
            'legs' => fn ($q) => $q->orderBy('leg_order'),
            'legs.segments' => fn ($q) => $q->orderBy('segment_order'),
        ]);
    }

    /**
     * Scope: constrain a query to a single flight by its public UUID.
     *
     * Usage: Flight::whereUuid($uuid)->firstOrFail();
     */
    public function scopeWhereUuid(Builder $query, string $uuid): Builder
    {
        return $query->where('uuid', $uuid);
    }
}
